### ISSUE TITLE
Allow resolving contributors to discord members during compile

### ISSUE THREAD

**Issue by Xetera** [the-programmers-hangout/website#17]
This would allow us to see the avatars and usernames of contributors. We could even go as far as to fetching the roles too so we can have a discord-like hovercards for users.

**Comment by supergrecko** [comment]
I think that fetching the avatar and the username (maybe grab the discord tag instead of username) is a good idea, but I personally think fetching the roles might be unnecessary.

- I don't think it's very useful and I doubt it'll be used very often
- Not too sure how relevant that information is
- Not sure what else we'd put on the cards

**Comment by Xetera** [comment]
Yeah not set on the roles thing, probably not going to happen. We already have a bot in TPH that we can use to get this information so I'll probably be using that.

The TPH bot people are interested in writing a backend for this so we might actually be able to fetch live data from a bot directly at some point.
