### ISSUE TITLE
Cannot view resource & archive pages during development on Windows

### ISSUE THREAD

**Issue by puremana** [the-programmers-hangout/website#214]
All resources show a 404 page when running `npm run start` on Windows 10. Node version 12.14.1

![image](https://user-images.githubusercontent.com/2869411/73126590-85b7d980-4019-11ea-9442-04e2d5abacb4.png)

When running the same command with the same version of node on Ubuntu 16.04 I can view the resources just fine.

![image](https://user-images.githubusercontent.com/2869411/73126637-37570a80-401a-11ea-90af-cad6a4711ed7.png)

Archive pages show a blank screen on windows (not even a 404 page) but work fine using Ubuntu. (i.e http://localhost:8000/archives/what-is-docker.md)

**Comment by mahanthathreyee** [comment]
This also occurs when built in windows (`gatsby build` and `gatsby serve`)
But rather than 404, it goes to the homepage for me

Node version 12.14.1, cloned the latest master branch

Ran on Virtualbox (Windows 10, browsers used: Edge and Firefox)
VM Details: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

![ezgif com-optimize](https://user-images.githubusercontent.com/26182655/73136548-d14ba100-4074-11ea-9734-7db1a851d54d.gif)

**Comment by veksen** [comment]
As much as I'd like to solve this, I don't use Windows for development, so it's hard for me to investigate. If anybody wants to explore, feel free!

**Comment by puremana** [comment]
If I remember correctly I believe the issue was related to how Gatsby was building the urls on windows
