### ISSUE TITLE
Sticky header bar breaks on scroll in mobile viewports

### ISSUE THREAD

**Issue by Xetera** [the-programmers-hangout/website#421]
![image](https://user-images.githubusercontent.com/24978328/135684304-f3ad9e5b-6f04-41d7-ac41-2864dd9dc596.png)

This behavior only really makes sense in desktop. Ideally the stickiness should be disabled in mobile mode completely.

**Comment by oof2win2** [comment]
The bug seems to be appearing on some pages only. The Emacs archive page works fine, but Elixir doesn't on the other hand (presents the issue above). Emacs rather shows this issue.
<img width="381" alt="Screenshot 2021-10-02 at 0 08 45" src="https://user-images.githubusercontent.com/23482862/135691318-c9fa9314-a6b7-4464-89be-74c698a998db.png">
